import "./global.css";

import AuthProvider from "../components/AuthProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body style={{backgroundColor:"#E6F3F3"}}>{children}</body>
      </AuthProvider>
    </html>
  );
}
