export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({
  children,
  courses,
  schedule,
}: {
  children: React.ReactNode;
  courses: React.ReactNode;
  schedule: React.ReactNode;
}) {
  return (
    <>
      <div>{children}</div>
      <div className="flex justify-between">
        <div>{courses}</div>
        <div>{schedule}</div>
      </div>
    </>
  );
}
