// import React, {Suspense , lazy} from "react";

import Box from "@mui/material/Box";
import { Grid, Paper, Typography} from "@mui/material";

// const Courses = lazy(()=>import("./@courses/page"));

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({
  children,
  courses,
  schedule,
}: {
  children: React.ReactNode;
  courses: React.ReactNode;
  schedule: React.ReactNode;
}) {

  return (
    <>
      <div>{children}</div>
      <Box sx={{ p: 2 }}>
        <Grid container spacing={2}>
          <Grid item xs={12} md={9}>
              {courses}
              {/* <Suspense fallback={<div>Loading courses...</div>}>
                <Courses />
              </Suspense> */}
          </Grid>
          <Grid item xs={12} md={3}>
              {schedule}
          </Grid>
        </Grid>
      </Box>
    </>
  );
}
