// import React, {Suspense , lazy} from "react";

import Box from "@mui/material/Box";
import { Grid, Paper, Typography} from "@mui/material";

// const Courses = lazy(()=>import("./@courses/page"));

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({
  children,
  courses,
  schedule,
}: {
  children: React.ReactNode;
  courses: React.ReactNode;
  schedule: React.ReactNode;
}) {

  return (
    <>
      <div>{children}</div>
      <Box sx={{ p: 2 }}>
        <Grid container spacing={2}>
          <Grid item xs={12} md={9}>
            <Paper
              style={{
                padding: "16px",
                textAlign: "center",
                backgroundColor: "#29b6f6",
                color:"white"
              }}
            >
              {courses}
              {/* <Suspense fallback={<div>Loading courses...</div>}>
                <Courses />
              </Suspense> */}
            </Paper>
          </Grid>
          <Grid item xs={12} md={3}>
            <Paper
              style={{
                padding: "16px",
                textAlign: "center",
                backgroundColor: "#29b6f6",
              }}
            >
              {schedule}
            </Paper>
          </Grid>
        </Grid>
      </Box>
    </>
  );
}
