import Box from "@mui/material/Box";
import { Grid} from "@mui/material";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({
  children,
  courses,
  schedule,
}: {
  children: React.ReactNode;
  courses: React.ReactNode;
  schedule: React.ReactNode;
}) {
  return (
    <>
      <div>{children}</div>
      <Box sx={{ p: 2 }}>
        <Grid container spacing={2}>
          <Grid item xs={12} md={9}>
            {courses}
          </Grid>
          <Grid item xs={12} md={3}>
              {schedule}
          </Grid>
        </Grid>
      </Box>
    </>
  );
}
